/* eslint-disable */
// Generated by unplugin-vue-components
export {}

declare module 'vue' {
  export interface GlobalComponents {
    UtilButton: typeof import('./components/Utils/UtilButton.vue')['default']
  }
}
